#!/bin/bash
cd /tmp/rom
rm -rf .repo

source build/envsetup.sh
lunch lighthouse_miatoll-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl bashupload.com -T $1

make_metalava(){
	mka api-stubs-docs -j16
	mka system-api-stubs-docs -j16
	mka test-api-stubs-docs -j16
}

make_rom(){
	make bacon -j16
	zip=$(up out/target/product/miatoll/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 4500 && kill "$!"
