#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/noob99.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf noob99.tar.gz
echo "unzip done"
find noob99.tar.gz -delete
